# Generated by Django 4.2 on 2025-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='position',
            field=models.CharField(default='President', max_length=100),
            preserve_default=False,
        ),
    ]
