# Generated by Django 4.2 on 2025-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_attorney_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='practice_area',
            field=models.CharField(default='Criminal law, Corperate Law, Business Law', max_length=200),
            preserve_default=False,
        ),
    ]
