# Generated by Django 4.2 on 2025-06-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_attorney_practice_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('seo_title', models.CharField(blank=True, help_text='SEO title', max_length=255)),
                ('seo_description', models.CharField(blank=True, help_text='SEO meta description', max_length=500)),
                ('seo_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=255)),
            ],
        ),
    ]
