# Generated by Django 4.2 on 2025-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='email',
            field=models.EmailField(default='rurl-amos@dunamislawfirm.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attorney',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='phone',
            field=models.CharField(default='+1234567890', max_length=30),
            preserve_default=False,
        ),
    ]
