# Generated by Django 4.2 on 2025-06-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_attorney_email_attorney_linkedin_url_attorney_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='flaticon',
            field=models.CharField(blank=True, help_text='for flaticon icon after the -', max_length=50),
        ),
    ]
