# Generated by Django 4.2 on 2025-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_service_flaticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
