# Generated by Django 4.2 on 2025-06-14 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
